filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-logs-%{+yyyy.MM.dd}"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

logging.level: info
